name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make

    - name: Build
      run: make

  functional-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc make

    - name: Build and Run
      run: make; make run

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Uncrustify
      run: sudo apt-get update && sudo apt-get install -y uncrustify

    - name: Run Uncrustify and check for diffs
      run: |
        find . -type f -name '*.c' -o -name '*.h' | xargs uncrustify -c test/uncrustify.cfg --replace --no-backup
        git diff --exit-code || (echo "Code was not formatted correctly" && exit 1)
